apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 732987445176.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 732987445176.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: "6033e266"
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
